# Generated by Django 4.0 on 2021-12-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('title', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=40)),
                ('url', models.CharField(max_length=40)),
            ],
        ),
    ]
