# Generated by Django 4.0 on 2021-12-28 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0002_alter_job_company_alter_job_title_alter_job_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Job',
            new_name='GetInfo',
        ),
    ]
