# Generated by Django 4.0 on 2022-01-03 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0003_rename_job_getinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='getinfo',
            name='word',
            field=models.CharField(default='', max_length=40),
        ),
    ]
